USE [master]
GO

/****** Object:  Database [stockmarket]    Script Date: 03/20/2019 01:31:02 ******/
CREATE DATABASE [stockmarket] ON  PRIMARY 
( NAME = N'stockmarket', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\stockmarket.mdf' , SIZE = 2304KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'stockmarket_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\stockmarket_log.LDF' , SIZE = 504KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [stockmarket] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [stockmarket].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [stockmarket] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [stockmarket] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [stockmarket] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [stockmarket] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [stockmarket] SET ARITHABORT OFF 
GO

ALTER DATABASE [stockmarket] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [stockmarket] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [stockmarket] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [stockmarket] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [stockmarket] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [stockmarket] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [stockmarket] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [stockmarket] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [stockmarket] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [stockmarket] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [stockmarket] SET  ENABLE_BROKER 
GO

ALTER DATABASE [stockmarket] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [stockmarket] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [stockmarket] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [stockmarket] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [stockmarket] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [stockmarket] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [stockmarket] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [stockmarket] SET  READ_WRITE 
GO

ALTER DATABASE [stockmarket] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [stockmarket] SET  MULTI_USER 
GO

ALTER DATABASE [stockmarket] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [stockmarket] SET DB_CHAINING OFF 
GO

